### ISSUE TITLE
How the FelicityEgtb add some into the custom position?

### ISSUE THREAD

**Issue by ETERCYBER** [nguyenpham/FelicityEgtb#1]
I see some pre-generated Egtb in the directory, but I don't know how these data are generated. I have seen all the functions in the source code are read. Is it possible to create a tool to add and modify these databases?

**Comment by nguyenpham** [comment]
To create data we use an own EGTB generator for Xiangqi. It is still in development and not enough functions/completed for public uses. Sorry
