### ISSUE TITLE
EGTB Viewer possible?

### ISSUE THREAD

**Issue by kenpchess** [nguyenpham/FelicityEgtb#4]
By the way, pham, could you create a egtb Viewer program that would allow us to browse the created EGTBs? Thank you in advance if it is possible. - kenpchess

**Comment by nguyenpham** [comment]
Sure, that is planned. I will integrate with Banksia GUI. Firstly for checking, and studying in a visual way. However, that version (BSG integrated with Felicity EGTB) will be released only when the EGTB becomes good and stable enough.

BWT, the EGTB generator has already a feature to probe any chess position (give it a FEN string in the parameter).

**Comment by nguyenpham** [comment]
The special BSG for Xiangqi (Chinese chess) has been tested with Felicity EGTB. It works well.
<img width="781" alt="Screenshot 2024-07-08 at 10 55 00 am" src="https://github.com/nguyenpham/FelicityEgtb/assets/1370755/bbb647ff-ba23-4e87-8182-ee8678351757">

**Comment by nguyenpham** [comment]
<img width="996" alt="Screenshot 2024-07-14 at 8 52 25 pm" src="https://github.com/user-attachments/assets/2e1f76f6-7ca4-4957-ae09-e8150ca87437">
BanksiaGUI with Felicity EGTB
